# Generated by Django 5.2.12 on 2026-03-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["order"],
                "verbose_name": "Option de réponse",
                "verbose_name_plural": "Options de réponses",
            },
        ),
        migrations.AddField(
            model_name="option",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
