# Generated by Django 5.2.12 on 2026-03-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_builder", "0002_alter_option_options_option_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Texte court"),
                    ("textarea", "Paragraphe (Texte long)"),
                    ("number", "Nombre"),
                    ("select", "Choix unique"),
                    ("textarea", "Paragraphe (Texte long)"),
                    ("date", "Date"),
                    ("image", "Photo/Image"),
                ],
                max_length=20,
            ),
        ),
    ]
