# Generated by Django 5.2.12 on 2026-03-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey_builder", "0003_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Soumission",
                "verbose_name_plural": "Soumissions",
            },
        ),
    ]
