# Generated by Django 5.2.12 on 2026-03-06 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_builder", "0004_alter_submission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="uid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
