# Generated by Django 5.2.12 on 2026-03-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_builder", "0005_survey_uid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={"verbose_name": "Enquête", "verbose_name_plural": "Enquêtes"},
        ),
        migrations.AlterField(
            model_name="survey",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Enquête visible sur le site"
            ),
        ),
    ]
