# Generated by Django 5.2.12 on 2026-03-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_builder", "0006_alter_survey_options_alter_survey_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="file_upload",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="enquete/responses/%Y/%m/",
                verbose_name="Fichier joint (Image/Audio)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="dependency_value",
            field=models.CharField(
                blank=True,
                help_text="Valeur de l'option qui débloque cette question",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_questions",
                to="survey_builder.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("section", "---Titre de Section / Groupe---"),
                    ("text", "Texte court"),
                    ("textarea", "Paragraphe (Texte long)"),
                    ("number", "Nombre"),
                    ("select", "Choix unique"),
                    ("date", "Date"),
                    ("image", "Photo/Image"),
                    ("audio", "Enregistrement audio"),
                ],
                max_length=20,
            ),
        ),
    ]
