# Generated by Django 5.2.12 on 2026-03-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "survey_builder",
            "0007_answer_file_upload_question_dependency_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="help_text",
            field=models.TextField(
                blank=True,
                help_text="Texte descriptif qui s'affiche sous le titre ou la question.",
                null=True,
                verbose_name="Description / Aide",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("Entete", "-- Titre illustratif(Regroupement)---"),
                    ("section", "Nouvelle section (Changement de page)"),
                    ("text", "Texte court"),
                    ("textarea", "Paragraphe (Texte long)"),
                    ("number", "Nombre"),
                    ("select", "Choix unique"),
                    ("date", "Date"),
                    ("image", "Photo/Image"),
                    ("audio", "Enregistrement audio"),
                ],
                max_length=20,
            ),
        ),
    ]
