# Generated by Django 5.2.12 on 2026-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_builder", "0008_question_help_text_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("Entete", "-- Titre illustratif(Regroupement)---"),
                    ("section", "Nouvelle section (Changement de page)"),
                    ("text", "Texte court"),
                    ("textarea", "Paragraphe (Texte long)"),
                    ("number", "Nombre"),
                    ("select", "Choix unique (Liste)"),
                    ("checkbox", "Choix multiples (Cases)"),
                    ("date", "Date"),
                    ("image", "Photo/Image"),
                    ("audio", "Enregistrement audio"),
                ],
                max_length=20,
            ),
        ),
    ]
