# Generated by Django 5.2.12 on 2026-03-04 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="statfile",
            name="authorized_users",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_stats", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="statfile",
            name="is_protected",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="UserFileAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stat_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statapp.statfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "stat_file")},
            },
        ),
    ]
