# Generated by Django 5.2.12 on 2026-03-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0002_statfile_authorized_users_statfile_is_protected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statfile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
