# Generated by Django 5.2.12 on 2026-03-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0003_statfile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statfile",
            name="slug",
            field=models.SlugField(blank=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
