# Generated by Django 5.2.12 on 2026-03-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0004_alter_statfile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statfile",
            name="file",
            field=models.FileField(
                upload_to="privatefold/stats_uploads/%Y/%m/",
                verbose_name="Fichier (CSV/Excel)",
            ),
        ),
    ]
