# Generated by Django 5.2.12 on 2026-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0005_alter_statfile_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Visible sur le site"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
