# Generated by Django 5.2.12 on 2026-03-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0006_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statfile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Fichier statistique",
                "verbose_name_plural": "Fichiers statistiques",
            },
        ),
        migrations.AlterField(
            model_name="statfile",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Visible sur le site"
            ),
        ),
    ]
