# Generated by Django 5.2.12 on 2026-03-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0008_statvariable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statvariable",
            name="unit",
        ),
    ]
