# Generated by Django 5.2.12 on 2026-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0009_remove_statvariable_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Validée pour le menu"
            ),
        ),
    ]
