# Generated by Django 5.2.12 on 2026-03-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0010_category_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_active",
        ),
    ]
