# Generated by Django 5.2.12 on 2026-03-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0011_remove_category_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la catégorie"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Validée (Visible)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Catégorie de Variable",
                "ordering": ["title"],
            },
        ),
        migrations.AlterField(
            model_name="statvariable",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="statapp.variablecategory",
            ),
        ),
    ]
