# Generated by Django 5.2.12 on 2026-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0012_variablecategory_alter_statvariable_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variablecategory",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Nom de la catégorie",
            ),
        ),
    ]
