# Generated by Django 5.2.12 on 2026-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0013_alter_variablecategory_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Titre de la catégorie",
            ),
        ),
    ]
