# Generated by Django 5.2.12 on 2026-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0014_alter_category_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                default=1,
                max_length=100,
                unique=True,
                verbose_name="Titre de la catégorie",
            ),
            preserve_default=False,
        ),
    ]
