# Generated by Django 5.2.12 on 2026-03-18 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0019_alter_statvariable_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=255, verbose_name="Nom du document"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Notes / Description"),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="archives_agence/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "csv",
                                    "png",
                                    "jpg",
                                ]
                            )
                        ],
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "ajoute_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Agence",
                "verbose_name_plural": "Documents Agence",
                "ordering": ["-date_upload"],
            },
        ),
    ]
