# Generated by Django 5.2.12 on 2026-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statapp", "0021_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
